@extends('master')
@section('content_more')
<nav id="navbar-example2" class="navbar bg-light px-3 mb-3">
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" href="#scrollspyHeading1">Hasan Amanh</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#scrollspyHeading2">Ahmed Yasen</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#scrollspyHeading3">Osama omer</a></li>
        <li><a class="dropdown-item" href="#scrollspyHeading4">khaled fares</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#scrollspyHeading5">Sami Johan</a></li>
      </ul>
    </li>
  </ul>
</nav>
<div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" class="scrollspy-example bg-light p-3 rounded-2" tabindex="0">
  <h4 id="scrollspyHeading1">Hasan Amanh</h4>
  <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, molestias autem. Ex eius sint labore excepturi ullam. Reprehenderit pariatur, amet eveniet provident, explicabo alias itaque nesciunt, unde voluptas soluta maiores! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloremque officiis repudiandae fugit soluta, tempore optio ut obcaecati debitis nisi atque vero saepe iste laborum labore laboriosam facilis praesentium. Esse! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem, placeat veniam doloribus neque, quaerat ducimus ipsam facilis sed consectetur, molestias accusamus dignissimos consequatur. Commodi et ullam sequi modi tempore corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo ab voluptatem eius molestiae officiis, voluptatum autem tempora. Amet beatae facilis sed quo, praesentium corporis deserunt neque, cum unde explicabo cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo, quisquam quas! Iusto, error inventore? Cupiditate consequuntur totam inventore ducimus iusto. Provident, vel earum. Praesentium repellat ipsam architecto totam saepe. Dolorum!</p>
  <h4 id="scrollspyHeading2">Ahmed Yasen</h4>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum mollitia distinctio vitae adipisci, porro asperiores quos quod, nihil, odio nemo iste voluptatum incidunt excepturi repellendus? Id saepe mollitia placeat atque. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloremque officiis repudiandae fugit soluta, tempore optio ut obcaecati debitis nisi atque vero saepe iste laborum labore laboriosam facilis praesentium. Esse! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem, placeat veniam doloribus neque, quaerat ducimus ipsam facilis sed consectetur, molestias accusamus dignissimos consequatur. Commodi et ullam sequi modi tempore corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo ab voluptatem eius molestiae officiis, voluptatum autem tempora. Amet beatae facilis sed quo, praesentium corporis deserunt neque, cum unde explicabo cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo, quisquam quas! Iusto, error inventore? Cupiditate consequuntur totam inventore ducimus iusto. Provident, vel earum. Praesentium repellat ipsam architecto totam saepe. Dolorum!</p>
  <h4 id="scrollspyHeading3">Osama omer</h4>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum mollitia distinctio vitae adipisci, porro asperiores quos quod, nihil, odio nemo iste voluptatum incidunt excepturi repellendus? Id saepe mollitia placeat atque. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloremque officiis repudiandae fugit soluta, tempore optio ut obcaecati debitis nisi atque vero saepe iste laborum labore laboriosam facilis praesentium. Esse! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem, placeat veniam doloribus neque, quaerat ducimus ipsam facilis sed consectetur, molestias accusamus dignissimos consequatur. Commodi et ullam sequi modi tempore corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo ab voluptatem eius molestiae officiis, voluptatum autem tempora. Amet beatae facilis sed quo, praesentium corporis deserunt neque, cum unde explicabo cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo, quisquam quas! Iusto, error inventore? Cupiditate consequuntur totam inventore ducimus iusto. Provident, vel earum. Praesentium repellat ipsam architecto totam saepe. Dolorum!</p>
  <h4 id="scrollspyHeading4">khaled fares</h4>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum mollitia distinctio vitae adipisci, porro asperiores quos quod, nihil, odio nemo iste voluptatum incidunt excepturi repellendus? Id saepe mollitia placeat atque. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloremque officiis repudiandae fugit soluta, tempore optio ut obcaecati debitis nisi atque vero saepe iste laborum labore laboriosam facilis praesentium. Esse! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem, placeat veniam doloribus neque, quaerat ducimus ipsam facilis sed consectetur, molestias accusamus dignissimos consequatur. Commodi et ullam sequi modi tempore corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo ab voluptatem eius molestiae officiis, voluptatum autem tempora. Amet beatae facilis sed quo, praesentium corporis deserunt neque, cum unde explicabo cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo, quisquam quas! Iusto, error inventore? Cupiditate consequuntur totam inventore ducimus iusto. Provident, vel earum. Praesentium repellat ipsam architecto totam saepe. Dolorum!</p>
  <h4 id="scrollspyHeading5">Sami Johan</h4>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum mollitia distinctio vitae adipisci, porro asperiores quos quod, nihil, odio nemo iste voluptatum incidunt excepturi repellendus? Id saepe mollitia placeat atque. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem doloremque officiis repudiandae fugit soluta, tempore optio ut obcaecati debitis nisi atque vero saepe iste laborum labore laboriosam facilis praesentium. Esse! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rem, placeat veniam doloribus neque, quaerat ducimus ipsam facilis sed consectetur, molestias accusamus dignissimos consequatur. Commodi et ullam sequi modi tempore corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo ab voluptatem eius molestiae officiis, voluptatum autem tempora. Amet beatae facilis sed quo, praesentium corporis deserunt neque, cum unde explicabo cupiditate! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Explicabo, quisquam quas! Iusto, error inventore? Cupiditate consequuntur totam inventore ducimus iusto. Provident, vel earum. Praesentium repellat ipsam architecto totam saepe. Dolorum!</p>
</div>
@endsection
